{% set name = "assimp" %}
{% set version = "5.3.1" %}
{% set sha256 = "fc2b858ff19b176484e4fbb6c78c0f1df05eb156" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/assimp/assimp/archive/v{{ version }}.tar.gz
  sha1: {{ sha256 }}

build:
  number: 3
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - libboost-devel
    - zlib
  run:
    - zlib

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  files:
    - test
  commands:
    - test -f $PREFIX/include/assimp/anim.h  # [unix]
    - test -f $PREFIX/lib/libassimp${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\assimp\anim.h exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\assimp.lib exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\assimp.dll exit 1  # [win]

about:
  home: https://assimp.org/
  summary: A library to import and export various 3d-model-formats including scene-post-processing to generate missing render data.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jorisv
    - traversaro
    - wolfv
    - jcarpent
