{% set name = "assimp" %}
{% set version = "5.0.1" %}
{% set sha256 = "f148ba31dc1e7e00e59cc09b25535af997dc1998" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/assimp/assimp/archive/v{{ version }}.tar.gz
  sha1: {{ sha256 }}
  patches:
    - patch.diff  # [linux]
    - fix_cmake_config.diff
    - do_not_export_debug_symbols_gcc.patch

build:
  number: 7
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - boost-cpp
    - zlib
  run:
    - boost-cpp
    - zlib

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [not win]
    - cmake
  files:
    - test
  commands:
    - test -f $PREFIX/include/assimp/anim.h  # [unix]
    - test -f $PREFIX/lib/libassimp${SHLIB_EXT}  # [unix]
    - if exist %LIBRARY_PREFIX%\include\assimp\anim.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\assimp-vc140-mt.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\bin\assimp-vc140-mt.dll (exit 0) else (exit 1)  # [win]

about:
  home: https://assimp.org/
  summary: A library to import and export various 3d-model-formats including scene-post-processing to generate missing render data.
  license: Modified BSD
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - jcarpent
