travis:
  secure:
    BINSTAR_TOKEN: AGzkKh9asznsEYrstBqFe6ycN2X78SHdIKQ7DmMfRW9G/mXjoQ5PU7or2E9eyB45FehVqzM2TO6KkpyCRiYtr6arsKw4d6Z3i0CPMm2zpnM50QIp1J5TlsopNrCn4+tPkQMe6n55H72yQGxAhbfHuX0rk53rNvCsELGj9uuj4NcRvCFERzEnxUuvrbgAMCIPwCkIVv6gUU+3zAqJ8vvOnTpo4UQo1EJK11FKfeZMCpczLXqohLXHdG1IJTAO6I/lA+3GuAFty8aBonSKmlz7/NsM7DFVs4C/751mWreRWIG4byFwQnKsFyfHbArcfLBkvz7SMvMI0RP9nT1IpeSuAVE+yeGI/uW91qnXK1yN+jhKhPvdD+IPy/f3lc4enlsZeXZ90Us+YzWmO6btuQ0A8ZF1RlivbK9GohJ9y4nG81cVh/1T6BadhnODGSjoHwIJqPGu0O/k0LRgjdExF1w48jdElI5jgCuS6VUl1MzGAKkqb2nPdz63AYmw2l/nXfqNdXjJDVX739g/38EmuB57lV5m7Hn53jztOLYeuMFuzH29Z1YvzQ2+8DyZLmqjqJTlHdVMQ1jHh/nOBVdRzlSJVSs7hUdRC1ZMkcR8oyazPvIXnw70E1dnXe3EWF4m8xiwX8h5qmAhh/Pus1NEFaXw3eZhyepaUYIEqTWm5vtQpWw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
